replicaCount: 3
replicaCountCanary: 1

canary:
  enabled: false
command: /app/entrypoints/mariner.sh
normal_deploy:
  enabled: true

version: mariner-v1

infisical:
  enabled: true
  host: https://infisical.dev.mariner.trident.bio/api
  namespace: default
  environment: dev

port: 80

image:
  repository: mariner-dev
  pullPolicy: Always
  tag: latest
  containerPort: 80
  livenessProbe:
    path: /
    port: 80
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1
  readinessProbe:
    path: /
    port: 80
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  product: mariner

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  annotations:
    alb.ingress.kubernetes.io/target-type: ip

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: mariner-backend-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  hosts:
  - host: dev.mariner.trident.bio
  tls:
  - hosts:
    - dev.mariner.trident.bio

istio_url: dev.mariner.trident.bio
istio_enabled: true
resources:
  limits:
    cpu: 2
    memory: 3Gi
  requests:
    cpu: 0.2
    memory: 1Gi

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 3
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
