{{- if .Values.istio_enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}
spec:
  host: {{ .Release.Name }}
  subsets:
  - name: v1
    labels:
      version: {{ .Release.Name }}-v1
  - name: v2
    labels:
      version: {{ .Release.Name }}-v2
{{- end }}
