default_context:
  project_name: 'mariner'
  project_slug: 'mariner'
  domain_main: 'mariner.trident.bio'
  domain_staging: 'stag.mariner.trident.bio'
  docker_swarm_stack_name_main: 'mariner-trident-bio'
  docker_swarm_stack_name_staging: 'stag-mariner-trident-bio'
  secret_key: '17d0be0cc06b63120770c707f14529c28d9af8d201523d022614f67eb04d8ec6'
  first_superuser: 'admin@mariner.trident.bio'
  first_superuser_password: '123456'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.mariner.trident.bio", "https://stag.mariner.trident.bio", "https://mariner.trident.bio", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.gmail.com'
  smtp_user: 'admin@mariner.trident.bio'
  smtp_password: '12345'
  smtp_emails_from_email: 'info@mariner.trident.bio'
  postgres_password: '123456'
  pgadmin_default_user: 'admin@mariner.trident.bio'
  pgadmin_default_user_password: '123456'
  traefik_constraint_tag: 'mariner.trident.bio'
  traefik_constraint_tag_staging: 'stag.mariner.trident.bio'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:123456'
  sentry_dsn: ''
  docker_image_prefix: 'mariner'
  docker_image_backend: 'marinerbackend'
  docker_image_celeryworker: 'marinerceleryworker'
  docker_image_frontend: 'marinerfrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
