version: "3.4"
services:
  webapp:
    depends_on:
      backend:
        condition: service_healthy
  backend:
    # Basic services to run the backend. Placing it here so main docker-compose
    # can be used along with multiple file applications
    depends_on:
      - db
      - mlflow
      - ray-worker
    volumes:
      - ./backend:/app:z
    environment:
      - JUPYTER=jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.custom_display_url=http://127.0.0.1:8888
  ray-head:
    volumes:
      - ./backend:/app:z
  ray-worker:
    volumes:
      - ./backend:/app:z

  e2e:
    depends_on:
      backend:
        condition: service_healthy
      webapp:
        condition: service_started
    volumes:
      - ./webapp:/e2e
      - ./webapp/cypress/e2e:/e2e/cypress/integration
      - ./backend/tests/data:/e2e/cypress/fixtures/data
