version: "3.4"
services:
  backend:
    depends_on:
      - db
      - mlflow
      - ray-worker
    environment:
      - RESTART=true
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - POSTGRES_URI=postgresql://postgres:123456@db:5432/app
      - SERVER_HOST=http://backend
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-Variable not set}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-Variable not set}
      - AWS_MODELS_BUCKEY=${AWS_MODELS_BUCKET-Variable not set}
      - AWS_REGION=${AWS_REGION-Variable not set}
      - AWS_DATASETS=${AWS_DATASETS-Variable not set}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID-Variable not set}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET-Variable not set}
    volumes:
      - ./cov:/app/cov
  mlflow:
    environment:
      - POSTGRES_SERVER=mlflowdb
      - POSTGRES_PORT=5432
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_ARTIFACT_URI=s3://dev-mariner-datasets
      - AWS_MODELS_BUCKET=s3://dev-mariner-datasets
      - SERVER_HOST=http://backend
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-Variable not set}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-Variable not set}
      - AWS_MODELS_BUCKEY=${AWS_MODELS_BUCKET-Variable not set}
      - AWS_REGION=${AWS_REGION-Variable not set}
      - AWS_DATASETS=${AWS_DATASETS-Variable not set}

  ray-head:
    environment:
      - SERVER_HOST=http://backend
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-Variable not set}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-Variable not set}
      - AWS_MODELS_BUCKEY=${AWS_MODELS_BUCKET-Variable not set}
      - AWS_REGION=${AWS_REGION-Variable not set}
      - AWS_DATASETS=${AWS_DATASETS-Variable not set}
  ray-worker:
    environment:
      - SERVER_HOST=http://backend
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-Variable not set}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-Variable not set}
      - AWS_MODELS_BUCKEY=${AWS_MODELS_BUCKET-Variable not set}
      - AWS_REGION=${AWS_REGION-Variable not set}
      - AWS_DATASETS=${AWS_DATASETS-Variable not set}
  db:
    volumes: []
  mlflowdb:
    volumes: []
