version: "3.3"
services:
  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports: 
      - "5432:5432"
  backend:
    image: '${DOCKER_IMAGE_BACKEND?Variable not set}:${TAG-latest}'
    depends_on:
      - db
    ports:
      - 80:80
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN?Variable not set}
      - SERVER_HOST=https://${DOMAIN?Variable not set}
      - SMTP_HOST=${SMTP_HOST}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}

  mlflowdb:
    image: postgres:12
    volumes:
      - app-mlflow-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports: 
      - "54321:5432"
  mlflow:
    depends_on:
      - mlflowdb
    build:
      context: .
      dockerfile: ./Dockerfile.mlflow
    env_file:
      - .env
    ports:
      - "5000:5000"
volumes:
  app-db-data:
  app-mlflow-data:

# networks:
#   traefik-public:
#     # Allow setting it to false for testing
#     external: ${TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL-true}
