version: "3.4"
services:
  backend:
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-Variable not set}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-Variable not set}
      - AWS_MODELS_BUCKEY=${AWS_MODELS_BUCKET-Variable not set}
      - AWS_REGION=${AWS_REGION-Variable not set}
      - AWS_DATASETS=${AWS_DATASETS-Variable not set}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID-Variable not set}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET-Variable not set}
    volumes:
      - ./cov:/app/cov
  mlflow:
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-Variable not set}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-Variable not set}
      - AWS_MODELS_BUCKEY=${AWS_MODELS_BUCKET-Variable not set}
      - AWS_REGION=${AWS_REGION-Variable not set}
      - AWS_DATASETS=${AWS_DATASETS-Variable not set}

  ray-head:
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-Variable not set}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-Variable not set}
      - AWS_MODELS_BUCKEY=${AWS_MODELS_BUCKET-Variable not set}
      - AWS_REGION=${AWS_REGION-Variable not set}
      - AWS_DATASETS=${AWS_DATASETS-Variable not set}
  ray-worker:
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-Variable not set}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-Variable not set}
      - AWS_MODELS_BUCKEY=${AWS_MODELS_BUCKET-Variable not set}
      - AWS_REGION=${AWS_REGION-Variable not set}
      - AWS_DATASETS=${AWS_DATASETS-Variable not set}
  db:
    volumes: []
  mlflowdb:
    volumes: []
