version: "3.4"
services:
  backend:
    depends_on:
      db:
        condition: service_healthy
      mlflow:
        condition: service_healthy
      ray-worker:
        condition: service_started
    healthcheck:
      test: curl -f http://backend:8000/health
      interval: 5s
      timeout: 15s
      retries: 15
    environment:
      - RESTART=true
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - POSTGRES_URI=postgresql://postgres:123456@db:5432/app
      # Make sure the attribute value is equal to the VITE_API_BASE_URL in the frontend
      - SERVER_HOST=http://backend:8000
      - SERVER_CORS=http://localhost:4173,http://localhost:4200,http://ray:10001,http://ray-worker:10001
      - WEBAPP_URL=http://localhost:4173
      - RAY_ADDRESS=ray://ray-head:10001
      - AUTHENTICATION_SECRET_KEY=secret
      - DEPLOYMENT_URL_SIGNATURE_SECRET_KEY=secret
      - APPLICATION_SECRET=secret
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-Variable not set}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-Variable not set}
      - AWS_MODELS_BUCKEY=${AWS_MODELS_BUCKET-Variable not set}
      - AWS_REGION=${AWS_REGION-Variable not set}
      - AWS_DATASETS=${AWS_DATASETS-Variable not set}
    volumes:
      - ./cov:/app/cov
  mlflow:
    depends_on:
      mlflowdb:
        condition: service_healthy
    environment:
      - MLFLOW_POSTGRES_URI=postgresql://postgres:123456@mlflowdb:5432/app
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - MLFLOW_ARTIFACT_URI=s3://dev-mariner-datasets
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-Variable not set}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-Variable not set}
      - AWS_MODELS_BUCKEY=${AWS_MODELS_BUCKET-Variable not set}
      - AWS_REGION=${AWS_REGION-Variable not set}

  ray-head:
    environment:
      - SERVER_HOST=http://backend:8000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-Variable not set}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-Variable not set}
      - AWS_MODELS_BUCKEY=${AWS_MODELS_BUCKET-Variable not set}
      - AWS_REGION=${AWS_REGION-Variable not set}
      - AWS_DATASETS=${AWS_DATASETS-Variable not set}
      - APPLICATION_SECRET=secret
  ray-worker:
    environment:
      - SERVER_HOST=http://backend:8000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID-Variable not set}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY-Variable not set}
      - AWS_MODELS_BUCKEY=${AWS_MODELS_BUCKET-Variable not set}
      - AWS_REGION=${AWS_REGION-Variable not set}
      - AWS_DATASETS=${AWS_DATASETS-Variable not set}
      - APPLICATION_SECRET=secret
  db:
    volumes: []
  mlflowdb:
    volumes: []
