"""add table deploy

Revision ID: 45aaeb3b5d40
Revises: 72b2fb3d122d
Create Date: 2023-04-27 14:45:43.170242

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "45aaeb3b5d40"
down_revision = "72b2fb3d122d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deploy",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("readme", sa.String(), nullable=True),
        sa.Column("shareUrl", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("STOPPED", "ACTIVE", "IDLE", name="deploymentstatus"),
            nullable=True,
        ),
        sa.Column(
            "rate_limit_unit",
            sa.Enum("MINUTE", "HOUR", "DAY", "MONTH", name="ratelimitunit"),
            nullable=True,
        ),
        sa.Column("rate_limit_value", sa.Integer(), nullable=True),
        sa.Column(
            "share_strategy",
            sa.Enum("PUBLIC", "PRIVATE", name="sharestrategy"),
            nullable=True,
        ),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"], ["modelversion.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_deploy_id"), "deploy", ["id"], unique=False)
    op.create_index(op.f("ix_deploy_name"), "deploy", ["name"], unique=True)
    op.create_index(op.f("ix_deploy_status"), "deploy", ["status"], unique=False)
    op.create_table(
        "sharepermissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deployment_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("organization", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["deployment_id"], ["deploy.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sharepermissions_id"), "sharepermissions", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sharepermissions_id"), table_name="sharepermissions")
    op.drop_table("sharepermissions")
    op.drop_index(op.f("ix_deploy_status"), table_name="deploy")
    op.drop_index(op.f("ix_deploy_name"), table_name="deploy")
    op.drop_index(op.f("ix_deploy_id"), table_name="deploy")
    op.drop_table("deploy")
    # ### end Alembic commands ###
