"""add check_status and created_by on modelversion

Revision ID: 6048519ddbce
Revises: 25191563d370
Create Date: 2023-10-09 15:23:27.878416

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6048519ddbce"
down_revision = "25191563d370"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "modelversion", sa.Column("check_status", sa.String(), nullable=True)
    )
    op.add_column(
        "modelversion",
        sa.Column("check_stack_trace", sa.String(), nullable=True),
    )
    op.add_column(
        "modelversion", sa.Column("created_by_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "modelversion",
        "user",
        ["created_by_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "modelversion", type_="foreignkey")
    op.drop_column("modelversion", "created_by_id")
    op.drop_column("modelversion", "check_stack_trace")
    op.drop_column("modelversion", "check_status")
    # ### end Alembic commands ###
