"""add_deployment_tables

Revision ID: 809377f238f8
Revises: 72b2fb3d122d
Create Date: 2023-04-28 20:29:59.293829

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "809377f238f8"
down_revision = "72b2fb3d122d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deployment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("readme", sa.String(), nullable=True),
        sa.Column("share_url", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "STOPPED",
                "ACTIVE",
                "IDLE",
                "STARTING",
                name="deploymentstatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "prediction_rate_limit_unit",
            sa.Enum("MINUTE", "HOUR", "DAY", "MONTH", name="RateLimitUnit"),
            nullable=True,
        ),
        sa.Column("prediction_rate_limit_value", sa.Integer(), nullable=True),
        sa.Column("show_training_data", sa.Boolean(), nullable=True),
        sa.Column(
            "share_strategy",
            sa.Enum("PUBLIC", "PRIVATE", name="sharestrategy"),
            nullable=True,
        ),
        sa.Column("model_version_id", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_version_id"], ["modelversion.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_deployment_id"), "deployment", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_deployment_name"), "deployment", ["name"], unique=True
    )
    op.create_index(
        op.f("ix_deployment_status"), "deployment", ["status"], unique=False
    )
    op.create_table(
        "sharepermission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deployment_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("organization", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["deployment_id"], ["deployment.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sharepermission_id"), "sharepermission", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sharepermission_id"), table_name="sharepermission")
    op.drop_table("sharepermission")
    op.drop_index(op.f("ix_deployment_status"), table_name="deployment")
    op.drop_index(op.f("ix_deployment_name"), table_name="deployment")
    op.drop_index(op.f("ix_deployment_id"), table_name="deployment")
    op.drop_table("deployment")
    # ### end Alembic commands ###
