"""add check_status columns

Revision ID: 8812f081252b
Revises: 25191563d370
Create Date: 2023-10-06 17:28:59.295822

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8812f081252b"
down_revision = "25191563d370"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "model", sa.Column("check_status", sa.String(), nullable=True)
    )
    op.add_column(
        "model", sa.Column("check_stack_trace", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model", "check_stack_trace")
    op.drop_column("model", "check_status")
    # ### end Alembic commands ###
