"""add oauth states

Revision ID: 8b6bfa79b5e9
Revises: 5a26e23f3634
Create Date: 2022-11-01 01:49:15.740862

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8b6bfa79b5e9"
down_revision = "5a26e23f3634"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauthstate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("provider", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oauthstate_state"), "oauthstate", ["state"], unique=False
    )
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_index(op.f("ix_oauthstate_state"), table_name="oauthstate")
    op.drop_table("oauthstate")
    # ### end Alembic commands ###
