"""make epochs and hyperparams nullable

Revision ID: e3a60c031614
Revises: 367adecac83c
Create Date: 2023-08-15 10:44:27.332033

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e3a60c031614"
down_revision = "367adecac83c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiment", "epochs", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiment", "epochs", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
