"""add deployment entity

Revision ID: 03cb39886a9f
Revises: 2f6015f0107c
Create Date: 2022-06-14 13:19:14.516505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03cb39886a9f'
down_revision = '2f6015f0107c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_name', table_name='model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_model_name', 'model', ['name'], unique=False)
    # ### end Alembic commands ###
