"""empty message

Revision ID: 284b6c793fa2
Revises: 9d8ee3ec4f15
Create Date: 2022-08-24 21:23:26.888287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284b6c793fa2'
down_revision = '9d8ee3ec4f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('split_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'split_column')
    # ### end Alembic commands ###
