"""add model entity

Revision ID: 2f6015f0107c
Revises: c6c90f1ad83c
Create Date: 2022-06-10 12:23:26.952597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6015f0107c'
down_revision = 'c6c90f1ad83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_model_name'), 'model', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_name'), table_name='model')
    op.drop_table('model')
    # ### end Alembic commands ###
