"""Add deployment entity

Revision ID: 69359f98ade3
Revises: 2f6015f0107c
Create Date: 2022-06-14 19:44:25.864233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69359f98ade3'
down_revision = '2f6015f0107c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_name'], ['model.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_index('ix_model_name', table_name='model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_model_name', 'model', ['name'], unique=False)
    op.drop_table('deployment')
    # ### end Alembic commands ###
