"""add relationship between model and dataset

Revision ID: 76b22dd4b526
Revises: eef736dd20e3
Create Date: 2022-07-14 23:37:48.303833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b22dd4b526'
down_revision = 'eef736dd20e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('dataset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'model', 'dataset', ['dataset_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.drop_column('model', 'dataset_id')
    # ### end Alembic commands ###
