"""Add column description entity

Revision ID: 9ba720656482
Revises: 19022f3b5dd5
Create Date: 2022-05-20 19:24:13.572925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba720656482'
down_revision = '19022f3b5dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('columndescription',
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('pattern', 'dataset_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('columndescription')
    # ### end Alembic commands ###
