"""add time columns to model modelversoin and dataset tables

Revision ID: a5532ddff889
Revises: 9b63ef759cef
Create Date: 2022-07-16 18:47:57.474281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5532ddff889'
down_revision = '9b63ef759cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('model', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('model', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('modelversion', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('modelversion', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modelversion', 'updated_at')
    op.drop_column('modelversion', 'created_at')
    op.drop_column('model', 'updated_at')
    op.drop_column('model', 'created_at')
    op.drop_column('dataset', 'updated_at')
    # ### end Alembic commands ###
