"""group column metadata in single entity

Revision ID: b0aeaff2380a
Revises: fda7857a2aa2
Create Date: 2022-08-11 13:00:58.062925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0aeaff2380a'
down_revision = 'fda7857a2aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('columndescription')
    op.add_column('columnsmetadata', sa.Column('description', sa.String(), nullable=True))
    op.add_column('columnsmetadata', sa.Column('pattern', sa.String(), nullable=False))
    op.drop_column('columnsmetadata', 'key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('columnsmetadata', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('columnsmetadata', 'pattern')
    op.drop_column('columnsmetadata', 'description')
    op.create_table('columndescription',
    sa.Column('pattern', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], name='columndescription_dataset_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pattern', 'dataset_id', name='columndescription_pkey')
    )
    # ### end Alembic commands ###
