"""persist model version with model config that originated it

Revision ID: eef736dd20e3
Revises: fe0301dab9b2
Create Date: 2022-07-08 11:05:00.388314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef736dd20e3'
down_revision = 'fe0301dab9b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelversion',
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['model_name'], ['model.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_name', 'model_version')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modelversion')
    # ### end Alembic commands ###
