"""add deployment

Revision ID: fe0301dab9b2
Revises: 474957253b99
Create Date: 2022-07-04 20:57:01.316627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0301dab9b2'
down_revision = '474957253b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_name'], ['model.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_index('ix_model_name', table_name='model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_model_name', 'model', ['name'], unique=False)
    op.drop_table('deployment')
    # ### end Alembic commands ###
