const DATASET_NAME = 'DATASET-CYPRESS';
const MODEL_SMILES_CATEGORICAL_NAME = 'TestSmilesCategorical';
const MODEL_SMILES_NUMERIC_NAME = 'TestSmilesNumeric';
const SOME_MODEL_NAME = 'SOME_MODEL_NAME';
const IRIS_DATASET_NAME = 'IRIS_DATASET_NAME';

export {
  DATASET_NAME,
  IRIS_DATASET_NAME,
  SOME_MODEL_NAME,
  MODEL_SMILES_CATEGORICAL_NAME,
  MODEL_SMILES_NUMERIC_NAME,
};
