const DATASET_NAME = 'DATASET-CYPRESS';
const MODEL_SMILES_CATEGORICAL_NAME = 'TestSmilesCategorical';
const MODEL_SMILES_NUMERIC_NAME = 'TestSmilesNumeric';

export {
  DATASET_NAME,
  MODEL_SMILES_CATEGORICAL_NAME,
  MODEL_SMILES_NUMERIC_NAME,
};
