"""add image_url to user

Revision ID: 00c8531f0f80
Revises: a8fca2463072
Create Date: 2022-12-07 11:49:24.142618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00c8531f0f80"
down_revision = "a8fca2463072"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("img_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "img_url")
    # ### end Alembic commands ###
