"""make created_by_id required in experiment entity

Revision ID: 2c8ec5cea42e
Revises: 4106d3f0da13
Create Date: 2023-01-20 15:55:28.058063

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2c8ec5cea42e"
down_revision = "4106d3f0da13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiment", "experiment_name", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "experiment", "created_by_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "experiment",
        "stage",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'RUNNING'::character varying"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "experiment",
        "stage",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'RUNNING'::character varying"),
    )
    op.alter_column(
        "experiment", "created_by_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "experiment", "experiment_name", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###
