"""add-url-to-event

Revision ID: 5a26e23f3634
Revises: 818d34e7127b
Create Date: 2022-09-09 22:38:40.247357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a26e23f3634'
down_revision = '818d34e7127b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'url')
    # ### end Alembic commands ###
