"""add description to model and make mlflow model version mapping nullable

Revision ID: 72b2fb3d122d
Revises: 2c8ec5cea42e
Create Date: 2023-01-23 12:04:26.845102

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '72b2fb3d122d'
down_revision = '2c8ec5cea42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('modelversion', 'mlflow_version',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('modelversion', 'mlflow_version',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('model', 'description')
    # ### end Alembic commands ###
