FROM node:16-alpine3.16 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm i -g npm
RUN npm install
COPY . /app
RUN npm run build:test

FROM node:16-alpine3.16 AS app

WORKDIR /app
COPY --from=builder /app/build ./build

RUN npm i -g serve
EXPOSE 3000
ENTRYPOINT serve -s build -l 3000

