FROM node:16-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . /app
RUN npm run build

FROM node:16-alpine AS app

WORKDIR /app
COPY --from=builder /app/build ./build

RUN npm i -g serve@14.2.0
EXPOSE 3000
ENTRYPOINT serve -s build -l 3000

