replicaCount: 3
replicaCountCanary: 1
command: /app/entrypoints/mlflow.sh


canary:
  enabled: false

normal_deploy:
  enabled: true

infisical:
  enabled: true
  host: https://infisical.dev.mariner.trident.bio/api
  namespace: default
  environment: dev

version: mlflow-v1

port: 4180

image:
  repository: mlflow
  pullPolicy: Always
  tag: latest
  containerPort: 4180
  # livenessProbe:
  #   path: /
  #   port: 4180
  #   periodSeconds: 30
  #   successThreshold: 1
  #   failureThreshold: 3
  #   timeoutSeconds: 1
  # readinessProbe:
  #   path: /
  #   port: 4180
  #   periodSeconds: 30
  #   successThreshold: 1
  #   failureThreshold: 3
  #   timeoutSeconds: 1

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  product: mlflow

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 4180
  annotations:
    alb.ingress.kubernetes.io/target-type: ip

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: mlflow-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  hosts:
  - host: mlflow.dev.trident.bio
  tls:
  - hosts:
    - mlflow.dev.trident.bio

istio_url: mlflow.dev.trident.bio
istio_enabled: true
resources:
  limits:
    cpu: 1
    memory: 4Gi
  requests:
    cpu: 0.2
    memory: 2Gi

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 3
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
