{{- if .Values.infisical.enabled -}}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ .Release.Name }}-infisical
spec:
  hostAPI: {{ .Values.infisical.host }}
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: {{ .Release.Name }}-infisical-token
        secretNamespace: {{ .Values.infisical.namespace }}
      secretsScope:
        envSlug: {{ .Values.infisical.environment }}
        secretsPath: "/"
  managedSecretReference:
    secretName: {{ .Release.Name }}-infisical
    secretNamespace: {{ .Values.infisical.namespace }}
{{- end }}