replicaCount: 1
replicaCountCanary: 1

canary:
  enabled: false
command: /app/entrypoints/mariner.sh
normal_deploy:
  enabled: true

version: mariner-v1

port: 80

image:
  repository: mariner-dev
  pullPolicy: Always
  tag: latest
  containerPort: 80
  livenessProbe:
    path: /health
    port: 80
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1
  readinessProbe:
    path: /health
    port: 80
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

imagePullSecrets:
  - name: regcred
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  product: mariner

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  annotations:
    alb.ingress.kubernetes.io/target-type: ip

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: '/health'
    kubernetes.io/ingress.class: 'nginx'
    meta.helm.sh/release-name: 'mariner-backend'
    meta.helm.sh/release-namespace: 'mariner'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
  - host: mariner.dev-devsvc.roche.com
  tls:
  - hosts:
    - mariner.dev-devsvc.roche.com

istio_url: dev.mariner.trident.bio
istio_enabled: false
resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 3
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
