replicaCount: 3
replicaCountCanary: 1
command: /app/entrypoints/ray-worker.sh

canary:
  enabled: false

normal_deploy:
  enabled: true

infisical:
  enabled: true
  host: https://infisical.dev.mariner.trident.bio/api
  namespace: ray
  environment: dev

version: ray-worker-v1

port: 5000

image:
  repository: 515402585597.dkr.ecr.us-east-1.amazonaws.com/ray-worker
  pullPolicy: Always
  tag: latest
  containerPort: 5000
  livenessProbe:
    path: /
    port: 5000
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1
  readinessProbe:
    path: /
    port: 5000
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  product: ray-worker

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 5000
  annotations:
    alb.ingress.kubernetes.io/target-type: ip

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: ray-worker-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
  hosts:
  - host: ray-worker.dev.trident.bio
  tls:
  - hosts:
    - ray-worker.dev.trident.bio

istio_url: ray-worker.dev.trident.bio

resources:
  limits:
    cpu: 4
    memory: 8Gi
  requests:
    cpu: 0.2
    memory: 4Gi

autoscaling:
  enabled: false
  # minReplicas: 1
  # maxReplicas: 3
  # targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
