name: Component & Tests CI
on:
  push:
    branches: [ "develop", "releases/**" ]
  pull_request:
    # Only when PRs are targeting develop or releases/** branches
    branches: [ develop, releases/** ]
  workflow_dispatch:
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1
    AWS_MODELS_BUCKET: s3://dev-mariner-datasets
    AWS_DATASETS: dev-mariner-datasets
    COMPOSE_HTTP_TIMEOUT: 600
    DOCKER_COMPOSE: "docker compose -f docker-compose.yml -f docker-compose-cicd.yml"
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: Build webapp
    #   run: make build-webapp DOCKER_COMPOSE="$DOCKER_COMPOSE"
    # - name: Install Cypress dependencies
    #   run: cd webapp && npm install cypress-vite
    # - name: Component tests
    #   run: make component-test DOCKER_COMPOSE="$DOCKER_COMPOSE"
    - name: E2E test
      # Runs even if previous steps failed (can be cancelled manually)
      if: '!cancelled()' 
      run: make e2e-test DOCKER_COMPOSE="$DOCKER_COMPOSE"
      