name: Cypress component tests
on:
  push:
    branches: [ "develop", "releases/**" ]
  pull_request:
    branches: [ develop, releases/** ]
  workflow_dispatch:
env:
  DOCKER_COMPOSE: "docker compose -f docker-compose.yml"
jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Component tests
      run: make component-test DOCKER_COMPOSE="$DOCKER_COMPOSE"
