name: Integration tests CI
on:
  pull_request:
    branches: [ "develop", "releases/**" ]
    types: [opened, synchronize]
    paths: [backend/**]
  workflow_dispatch:
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1
    AWS_MODELS_BUCKET: s3://dev-mariner-datasets
    AWS_DATASETS: dev-mariner-datasets
    POSTGRES_URI: postgresql://postgres:123456@db:5432/app
    MLFLOW_POSTGRES_URI: postgresql://postgres:123456@mlflowdb:5432/app
    RAY_ADDRESS: ray://ray:10001
    MLFLOW_TRACKING_URI: http://mlflow:5000
    APPLICATION_SECRET: secret
    AUTHENTICATION_SECRET_KEY: secret
    DEPLOYMENT_URL_SIGNATURE_SECRET_KEY: secret
    COMPOSE_HTTP_TIMEOUT: 600
    COMPOSE_USER: 1000:1000
    DOCKER_COMPOSE: "docker compose -f docker-compose.yml -f docker-compose-cicd.yml"
jobs:
  tests-backend-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and start services
      run: make start DOCKER_COMPOSE="$DOCKER_COMPOSE" CORE_SERVICES="backend ray-head ray-worker mlflow mlflowdb db"
    - name: Integration tests and get report
      run: bash -c "$DOCKER_COMPOSE exec -T backend bash scripts/test.sh -m pytest -m 'integration'"
