name: Continous Integration with Docker
on:
  pull_request:
    branches: [ "develop", "releases/**" ]
    types: [opened, synchronize]
    paths: [backend/**]
  workflow_dispatch:
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1
    AWS_MODELS_BUCKET: s3://dev-mariner-datasets
    AWS_DATASETS: dev-mariner-datasets
    GITHUB_CLIENT_ID: --
    GITHUB_CLIENT_SECRET: --
    COMPOSE_HTTP_TIMEOUT: 600
jobs:
  all-backend-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: E2E tests
      run: make test-e2e DOCKER_COMPOSE="docker compose -f docker-compose.yml -f docker-compose-cicd.yml"
    - name: Start services
      run: make start DOCKER_COMPOSE="docker compose -f docker-compose.yml -f docker-compose-cicd.yml"
    - name: Integration tests and get report
      run: docker compose -f docker-compose.yml -f docker-compose-cicd.yml exec -T backend bash scripts/test.sh -m pytest -m 'integration'
