name: End to End Tests CI
on:
  push:
    branches: [ "develop", "releases/**" ]
  pull_request:
    # Only when PRs are targeting develop or releases/** branches
    branches: [ develop, releases/** ]
  workflow_dispatch:
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1
    AWS_MODELS_BUCKET: s3://dev-mariner-datasets
    AWS_DATASETS: dev-mariner-datasets
    GITHUB_CLIENT_ID: --
    GITHUB_CLIENT_SECRET: --
    COMPOSE_HTTP_TIMEOUT: 600
    DOCKER_COMPOSE: "docker compose -f docker-compose.yml -f docker-compose-cicd.yml"
jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: E2E tests
      run: make test-e2e DOCKER_COMPOSE="$DOCKER_COMPOSE"
    - uses: actions/upload-artifact@v3
      with:
        name: e2e-cypress-videos
        path: ./webapp/cypress/videos
        if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn`
