name: Code Quality Analysis
on:
  pull_request:
    branches: [ "develop", "releases/**" ]
    types: [opened, synchronize]
  push:
    branches:
      - 'develop'
      - 'releases/**'
  workflow_dispatch:
    inputs:
      save_src:
        type: boolean
        description: Saves the branch linting results in the repo cache
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache Dependencies
      id: poetry-cache
      uses: actions/cache@v3
      with:
        path: /home/runner/.cache/pypoetry
        key: ${{ runner.os }}-poetry-cache
        restore-keys: ${{ runner.os }}-poetry-cache
    - name: Debug cache
      run: ls /home/runner/.cache/pypoetry
    - name: Cache Pylint results
      id: pylint-cache
      uses: actions/cache@v3
      with:
        path: /home/runner/.cache/pylint
        key: ${{ runner.os }}-pylint-cache
        restore-keys: ${{ runner.os }}-pylint-cache
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.3.2
        virtualenvs-create: false
        virtualenvs-in-project: false
        installer-parallel: true
    - name: Install project
      run: poetry install
    - name: Update target branch score (push)
      if: github.event_name == 'push'
      run: "poetry run python scripts/pylint_packages.py ${{ github.event.ref || 'develop' }} ${{ github.event.base_ref }} --save-new-target"

    - name: Update branch score (workflow_dispatch)
      if: github.event_name == 'workflow_dispatch'
      run: "poetry run python scripts/pylint_packages.py ${{ github.event.ref }} develop ${{ github.event.inputs.save_src && '--save-new-target' }}"

    - name: Check PR lint score improve (pull_request)
      if: github.event_name == 'pull_request'
      run: "poetry run python scripts/pylint_packages.py -- ${{ github.event.pull_request.base.ref }}"

    - name: Debug lint cache
      run: ls /home/runner/.cache/ && echo '-----' && ls /home/runner/.cache/pylint
