name: Build Minikube - Manual
on:
  push:
    branches:
      - 'minikube'
env:
  AWS_REGION: us-east-1
  IMAGE_TAG: ${{ github.sha }}
jobs:
  docker_image:
    name: docker_image
    runs-on: ubuntu-20.04
    env:
      ECR_REPOSITORY: mariner-minikube
    steps:
    - name: Build - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Build - Git Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
        persist-credentials: false
    - name: Build - Get ECR Repository
      run: |
        aws ecr describe-repositories --region $AWS_REGION --repository-names $ECR_REPOSITORY > /dev/null 2>&1 || \
          aws ecr create-repository --region $AWS_REGION  --repository-name $ECR_REPOSITORY
    - name: Build - Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build - Build and push image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f dockerfiles/Dockerfile.minikube .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY -a