name: Docker Image CI

on:
  pull_request:
    branches: [ "develop", "ci/configure-action" ]
    types: [opened, ready_for_review, review_requested, reopened]
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build containers and install dependencies
      run: docker-compose --env-file .env.test -f docker-compose-cicd.yml up -d --build
    - name: Build and test on Docker Compose. Fails when coverage is under 77%
      run: poetry run pre-commit run --hook-stage manual test
