name: Docker Image CI

on:
  pull_request:
    branches: [ "develop", "ci/configure-action" ]
    types: [opened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check style code standards
      run: sh scripts/check-format.sh
    - name: Check code quality
      run: sh scripts/lint.sh
      continue-on-error: true
    - name: Build and test on Docker Compose. Fails when coverage is under 77%
      run: pre-commit run --hook-stage manual test
