name: Docker Image CI

on:
  pull_request:
    branches: [ "develop", "ci/configure-action" ]
    types: [opened, reopened]
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: docker-layer-caching-tests-{hashFiles('poetry.lock')}-{hashFiles('dockerfiles/Dockerfile.local')}-{hashFiles('docker-compose-cicd.yml')}-{hashFiles('.env.test')}
        restore-keys: docker-layer-caching-Unit-tests-
    - name: Build containers and install dependencies
      run: docker-compose --env-file .env.test -f docker-compose-cicd.yml up -d --build
    - name: Build and test on Docker Compose. Fails when coverage is under 77%
      run: sh scripts/test.sh
