name: Docker Image CI

on:
  pull_request:
    branches: [ "develop", "ci/configure-action" ]
    types: [opened, ready_for_review, review_requested, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build containers
      run: docker-compose up -d --build
    - name: Check style code standards
      run: docker-compose exec backend sh scripts/check-format.sh
    - name: Check code quality
      run: docker-compose exec backend sh scripts/lint.sh
      continue-on-error: true
    - name: Build and test on Docker Compose. Fails when coverage is under 77%
      run: pre-commit run --hook-stage manual test
