name: Docker Image CI

on:
  pull_request:
    branches: [ "develop", "ci/configure-action" ]
    types: [opened, reopened]
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: us-east-1
    AWS_MODELS_BUCKET: s3://dev-mariner-datasets
    AWS_DATASETS: dev-mariner-datasets
    GITHUB_CLIENT_ID: --
    GITHUB_CLIENT_SECRET: --
    COMPOSE_HTTP_TIMEOUT: 600
jobs:
  all-backend-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build containers
      run: docker-compose -f docker-compose.yml -f docker-compose-cicd.yml build
    - name: Start services
      run: docker-compose -f docker-compose.yml -f docker-compose-cicd.yml up -d
      continue-on-error: true
    - name: Wait a bit
      run: sleep 10
    - name: Backend logs
      run: docker-compose -f docker-compose.yml -f docker-compose-cicd.yml logs backend mlflow ray-head
    - name: Run tests and get report
      run: docker-compose -f docker-compose.yml -f docker-compose-cicd.yml exec -T backend bash scripts/test.sh
