name: Deploy All Dev - Auto
on:
  push:
    branches:
      - develop
env:
  AWS_REGION: us-east-1
  IMAGE_TAG: ${{ github.sha }}
jobs:

  docker_image:
    name: docker_image
    runs-on: ubuntu-20.04
    env:
      ECR_REPOSITORY: mariner-template-dev
    steps:
    - name: Build - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Build - Git Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
        persist-credentials: false
    - name: Build - Get ECR Repository
      run: |
        aws ecr describe-repositories --region $AWS_REGION --repository-names $ECR_REPOSITORY > /dev/null 2>&1 || \
          aws ecr create-repository --region $AWS_REGION  --repository-name $ECR_REPOSITORY
    - name: Build - Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build - Build and push image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f dockerfiles/Dockerfile .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY -a
  mariner:
    name: Mariner
    runs-on: ubuntu-20.04
    env:
      ECR_REPOSITORY: mariner-template-dev
      DEPLOYMENT_NAME: mariner-backend
    steps:
    - name: Information
      env:
        BRANCH: ${{ github.event.inputs.branch }}
      run: |
        if [ -n "$BRANCH" ]
        then
          echo Deploying "$BRANCH" for "$DEPLOYMENT_NAME"
        else
          echo Deploying default branch for "$DEPLOYMENT_NAME"
        fi
    - name: Build - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Build - Git Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
        persist-credentials: false
    - name: Deploy - Setup Credentials
      id: setup-kubeconfig
      run: |
        aws eks --region $AWS_REGION update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
    - name: Deploy - Update Kubernetes Deployment
      id: deploy-to-eks
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        HEALTH_CHECK_URL: ${{ secrets.HEALTH_CHECK_URL }}
        CONFIGMAP: ${{ secrets.CONFIGMAP }}
        SECRETS: ${{ secrets.SECRETS }}
        REPLICA_COUNT: ${{ secrets.REPLICA_COUNT }}
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl &&\
        chmod +x ./kubectl &&\
        mv ./kubectl /usr/local/bin/kubectl &&\
        kubectl apply -f - <<< "$CONFIGMAP" 
        helm upgrade -i "$DEPLOYMENT_NAME" helm/helm-mariner/. \
          --set "replicaCount=$REPLICA_COUNT" \
          --set "image.repository=$ECR_REGISTRY/$ECR_REPOSITORY" \
          --set "image.livenessProbe.path=$HEALTH_CHECK_URL" \
          --set "image.readinessProbe.path=$HEALTH_CHECK_URL" \
          --set "istio_url=backend.${{ secrets.HOST_ZONE }}"
        kubectl rollout status "deployment/$DEPLOYMENT_NAME"

  mlflow:
    name: MLFlow
    runs-on: ubuntu-20.04
    env:
      ECR_REPOSITORY: mariner-template-dev
      DEPLOYMENT_NAME: mlflow
    steps:
    - name: Information
      env:
        BRANCH: ${{ github.event.inputs.branch }}
      run: |
        if [ -n "$BRANCH" ]
        then
          echo Deploying "$BRANCH" for "$DEPLOYMENT_NAME"
        else
          echo Deploying default branch for "$DEPLOYMENT_NAME"
        fi
    - name: Build - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Build - Git Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
        persist-credentials: false
    - name: Deploy - Setup Credentials
      id: setup-kubeconfig
      run: |
        aws eks --region $AWS_REGION update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
    - name: Deploy - Update Kubernetes Deployment
      id: deploy-to-eks
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        HEALTH_CHECK_URL: ${{ secrets.HEALTH_CHECK_URL_MLFLOW }}
        CONFIGMAP: ${{ secrets.CONFIGMAP }}
        REPLICA_COUNT: ${{ secrets.REPLICA_COUNT }}
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl &&\
        chmod +x ./kubectl &&\
        mv ./kubectl /usr/local/bin/kubectl &&\
        kubectl apply -f - <<< "$CONFIGMAP"
        helm upgrade -i "$DEPLOYMENT_NAME" helm/helm-mlflow/. \
          --set "replicaCount=$REPLICA_COUNT" \
          --set "image.repository=$ECR_REGISTRY/$ECR_REPOSITORY" \
          --set "image.livenessProbe.path=$HEALTH_CHECK_URL" \
          --set "image.readinessProbe.path=$HEALTH_CHECK_URL" \
          --set "istio_url=mlflow.${{ secrets.HOST_ZONE }}"
        kubectl rollout status "deployment/$DEPLOYMENT_NAME"
  ray-head:
    name: Ray Head
    runs-on: ubuntu-20.04
    env:
      ECR_REPOSITORY: mariner-template-dev
      DEPLOYMENT_NAME: ray-head
    steps:
    - name: Information
      env:
        BRANCH: ${{ github.event.inputs.branch }}
      run: |
        if [ -n "$BRANCH" ]
        then
          echo Deploying "$BRANCH" for "$DEPLOYMENT_NAME"
        else
          echo Deploying default branch for "$DEPLOYMENT_NAME"
        fi
    - name: Build - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Build - Git Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
        persist-credentials: false
    - name: Deploy - Setup Credentials
      id: setup-kubeconfig
      run: |
        aws eks --region $AWS_REGION update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
    - name: Deploy - Update Kubernetes Deployment
      id: deploy-to-eks
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        HEALTH_CHECK_URL: ${{ secrets.HEALTH_CHECK_URL_RAY_HEAD }}
        CONFIGMAP: ${{ secrets.CONFIGMAP_RAY_HEAD }}
        REPLICA_COUNT: ${{ secrets.REPLICA_COUNT }}
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl &&\
        chmod +x ./kubectl &&\
        mv ./kubectl /usr/local/bin/kubectl &&\
        kubectl apply -f - <<< "$CONFIGMAP"
        helm upgrade -i "$DEPLOYMENT_NAME" helm/helm-ray-head/.  -n ray \
          --set "replicaCount=$REPLICA_COUNT" \
          --set "image.repository=$ECR_REGISTRY/$ECR_REPOSITORY" \
          --set "image.livenessProbe.path=$HEALTH_CHECK_URL" \
          --set "image.readinessProbe.path=$HEALTH_CHECK_URL" \
          --set "istio_url=ray.${{ secrets.HOST_ZONE }}"
  ray-worker:
    name: Ray Worker
    runs-on: ubuntu-20.04
    env:
      ECR_REPOSITORY: mariner-template-dev
      DEPLOYMENT_NAME: ray-worker
    steps:
    - name: Information
      env:
        BRANCH: ${{ github.event.inputs.branch }}
      run: |
        if [ -n "$BRANCH" ]
        then
          echo Deploying "$BRANCH" for "$DEPLOYMENT_NAME"
        else
          echo Deploying default branch for "$DEPLOYMENT_NAME"
        fi
    - name: Build - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Build - Git Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
        persist-credentials: false
    - name: Deploy - Setup Credentials
      id: setup-kubeconfig
      run: |
        aws eks --region $AWS_REGION update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
    - name: Deploy - Update Kubernetes Deployment
      id: deploy-to-eks
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        HEALTH_CHECK_URL: ${{ secrets.HEALTH_CHECK_URL_RAY_WORKER }}
        CONFIGMAP: ${{ secrets.CONFIGMAP_RAY_WORKER }}
        REPLICA_COUNT: ${{ secrets.REPLICA_COUNT }}
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl &&\
        chmod +x ./kubectl &&\
        mv ./kubectl /usr/local/bin/kubectl &&\
        kubectl apply -f - <<< "$CONFIGMAP"
        helm upgrade -i "$DEPLOYMENT_NAME" helm/helm-ray-worker/.  -n ray \
          --set "replicaCount=$REPLICA_COUNT" \
          --set "image.repository=$ECR_REGISTRY/$ECR_REPOSITORY" \
          --set "image.livenessProbe.path=$HEALTH_CHECK_URL" \
          --set "image.readinessProbe.path=$HEALTH_CHECK_URL" \
          --set "istio_url=ray-worker.${{ secrets.HOST_ZONE }}"
