name: Deploy All Dev - Auto
on:
  push:
    branches:
      - develop
env:
  AWS_REGION: us-east-1
  IMAGE_TAG: ${{ github.sha }}
jobs:
  #This step builds and pushes the template image that will be used in all deployments.
  docker_image:
    name: docker_image
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    env:
      ECR_REPOSITORY: mariner-template-dev
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    #Checkout branch
    - name: Build - Git Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
    # Creates a new release
    - id: release
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: patch
    - name: Check Output Parameters
      run: |
        echo "Got tag name ${{ steps.release.outputs.tag_name }}"
        echo "Got release version ${{ steps.release.outputs.version }}"
        echo "Upload release artifacts to ${{ steps.release.outputs.upload_url }}"
    # Installs poetry and configures to use virtualenv
    # created in cwd()/.venv
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      if: steps.venv-cache.outputs.cache-hit != true
      with:
        version: 1.3.2
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Bump pyproject version
      run: |
        cd backend && \
        poetry version ${{ steps.release.outputs.version }}

    - name: Commit Release
      run: |
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Release ${{ steps.release.outputs.version }}"
        git push
    #Setup AWS Credentials using github secrets
    - name: Build - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    #Create or validade the ECR repository (Our private registry for docker images)
    - name: Build - Get ECR Repository
      run: |
        aws ecr describe-repositories --region $AWS_REGION --repository-names $ECR_REPOSITORY > /dev/null 2>&1 || \
          aws ecr create-repository --region $AWS_REGION  --repository-name $ECR_REPOSITORY
    #Authenticates to the ECR
    - name: Build - Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    #Build and push docker image
    - name: Build - Build and push image
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build --no-cache -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f dockerfiles/Dockerfile.cpu backend
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY -a
  #Deployment Mariner Backend
  mariner:
    name: Mariner
    runs-on: ubuntu-20.04
    needs: docker_image
    env:
      ECR_REPOSITORY: 515402585597.dkr.ecr.us-east-1.amazonaws.com/mariner-template-dev
      DEPLOYMENT_NAME: mariner-backend
    steps:
    #Setup AWS Credentials using github secrets
    - name: Build - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    #Checkout branch
    - name: Build - Git Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
        persist-credentials: false
    #Setup Kubernetes Authentication
    - name: Deploy - Setup Credentials
      id: setup-kubeconfig
      run: |
        aws eks --region $AWS_REGION update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
    #Deploy helm chart
    - name: Deploy - Update Kubernetes Deployment
      id: deploy-to-eks
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        HEALTH_CHECK_URL: ${{ secrets.HEALTH_CHECK_URL }}
        REPLICA_COUNT: ${{ secrets.REPLICA_COUNT }}
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl &&\
        chmod +x ./kubectl &&\
        mv ./kubectl /usr/local/bin/kubectl &&\
        helm upgrade -i "$DEPLOYMENT_NAME" infrastructure/helm/helm-mariner/. \
          --set "replicaCount=$REPLICA_COUNT" \
          --set "image.repository=$ECR_REPOSITORY" \
          --set "image.livenessProbe.path=$HEALTH_CHECK_URL" \
          --set "image.readinessProbe.path=$HEALTH_CHECK_URL" \
          --set "istio_url=backend.${{ secrets.HOST_ZONE }}"
        kubectl rollout status "deployment/$DEPLOYMENT_NAME"
  #Deployment MLFLOW
  mlflow:
    name: MLFlow
    runs-on: ubuntu-20.04
    needs: docker_image
    env:
      ECR_REPOSITORY: 515402585597.dkr.ecr.us-east-1.amazonaws.com/mariner-template-dev
      DEPLOYMENT_NAME: mlflow
    steps:
    #Setup AWS Credentials using github secrets
    - name: Build - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    #Checkout branch
    - name: Build - Git Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
        persist-credentials: false
    #Setup Kubernetes Authentication
    - name: Deploy - Setup Credentials
      id: setup-kubeconfig
      run: |
        aws eks --region $AWS_REGION update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
    #Deploy helm chart
    - name: Deploy - Update Kubernetes Deployment
      id: deploy-to-eks
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        HEALTH_CHECK_URL: ${{ secrets.HEALTH_CHECK_URL_MLFLOW }}
        REPLICA_COUNT: ${{ secrets.REPLICA_COUNT }}
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl &&\
        chmod +x ./kubectl &&\
        mv ./kubectl /usr/local/bin/kubectl &&\
        helm upgrade -i "$DEPLOYMENT_NAME" infrastructure/helm/helm-mlflow/. \
          --set "replicaCount=$REPLICA_COUNT" \
          --set "image.repository=$ECR_REPOSITORY" \
          --set "image.livenessProbe.path=$HEALTH_CHECK_URL" \
          --set "image.readinessProbe.path=$HEALTH_CHECK_URL" \
          --set "istio_url=mlflow.${{ secrets.HOST_ZONE }}"
        kubectl rollout status "deployment/$DEPLOYMENT_NAME"
  #Deployment Ray Head
  ray-head:
    name: Ray Head
    runs-on: ubuntu-20.04
    needs: docker_image
    env:
      ECR_REPOSITORY: 515402585597.dkr.ecr.us-east-1.amazonaws.com/mariner-template-dev
      DEPLOYMENT_NAME: ray-head
    steps:
    #Setup AWS Credentials using github secrets
    - name: Build - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    #Checkout branch
    - name: Build - Git Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
        persist-credentials: false
    #Setup Kubernetes Authentication
    - name: Deploy - Setup Credentials
      id: setup-kubeconfig
      run: |
        aws eks --region $AWS_REGION update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
    #Deploy helm chart
    - name: Deploy - Update Kubernetes Deployment
      id: deploy-to-eks
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        HEALTH_CHECK_URL: ${{ secrets.HEALTH_CHECK_URL_RAY_HEAD }}
        REPLICA_COUNT: ${{ secrets.REPLICA_COUNT }}
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl &&\
        chmod +x ./kubectl &&\
        mv ./kubectl /usr/local/bin/kubectl &&\
        helm upgrade -i "$DEPLOYMENT_NAME" infrastructure/helm/helm-ray-head/.  -n ray \
          --set "replicaCount=$REPLICA_COUNT" \
          --set "image.repository=$ECR_REPOSITORY" \
          --set "image.livenessProbe.path=$HEALTH_CHECK_URL" \
          --set "image.readinessProbe.path=$HEALTH_CHECK_URL" \
          --set "istio_url=ray.${{ secrets.HOST_ZONE }}"
  #Deployment Ray Worker
  ray-worker:
    name: Ray Worker
    runs-on: ubuntu-20.04
    needs: docker_image
    env:
      ECR_REPOSITORY: 515402585597.dkr.ecr.us-east-1.amazonaws.com/mariner-template-dev
      DEPLOYMENT_NAME: ray-worker
    steps:
    #Setup AWS Credentials using github secrets
    - name: Build - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    #Checkout branch
    - name: Build - Git Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}
        persist-credentials: false
    #Setup Kubernetes Authentication
    - name: Deploy - Setup Credentials
      id: setup-kubeconfig
      run: |
        aws eks --region $AWS_REGION update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }}
    #Deploy helm chart
    - name: Deploy - Update Kubernetes Deployment
      id: deploy-to-eks
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        HEALTH_CHECK_URL: ${{ secrets.HEALTH_CHECK_URL_RAY_WORKER }}
        REPLICA_COUNT: ${{ secrets.REPLICA_COUNT }}
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl &&\
        chmod +x ./kubectl &&\
        mv ./kubectl /usr/local/bin/kubectl &&\
        helm upgrade -i "$DEPLOYMENT_NAME" infrastructure/helm/helm-ray-worker/.  -n ray \
          --set "replicaCount=$REPLICA_COUNT" \
          --set "image.repository=$ECR_REPOSITORY" \
          --set "image.livenessProbe.path=$HEALTH_CHECK_URL" \
          --set "image.readinessProbe.path=$HEALTH_CHECK_URL" \
          --set "istio_url=ray-worker.${{ secrets.HOST_ZONE }}"
