name: SonarQube Scan
on:
  push:
    branches: [ sonarqube ]
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint with pylint
        run: |
          pylint --output-format=pylint_junit.JUnitReporter --fail-under=7.0 my_project > pylint-report.xml
      - name: Analyze with SonarQube
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          sonar-qube-url: 'https://sonarqube.dev.mariner.trident.bio'
          sonar-project-key: 'mariner'
          sonar-project-name: 'Mariner'
          sonar-project-version: '1.0'
          extra-properties: |
            sonar.python.pylint.reportPath=pylint-report.json

